--- 
abstract: object representing a property list
author: 
  - Alex Vandiver <alexmv@mit.edu>
distribution_type: module
generated_by: Module::Install version 0.70
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Data-Plist
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::ISA: 0
  DateTime: 0
  Encode: 0
  MIME::Base64: 0
  Scalar::Util: 0
  UNIVERSAL::isa: 0
  UNIVERSAL::require: 0
  XML::Writer: 0
version: 0.1
